driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: ubuntu-12.10
    run_list:
      - recipe[apt::default]
  - name: ubuntu-12.04
    run_list:
      - recipe[apt::defaul]
  - name: ubuntu-10.04
    run_list:
      recipe[apt::default]
  - name: debian-6
    driver_config:
      box: opscode-debian-6
      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_debian-6.0.7_provisionerless.box
    run_list: ["recipe[apt]"]
  - name: centos-6.4
  - name: centos-5.9

suites:
  - name: default
    run_list:
    - recipe[minitest-handler::default]
    - recipe[nginx::default]
  - name: source
    run_list:
    - recipe[minitest-handler::default]
    - recipe[nginx::source]
    attributes:
      nginx:
        install_method: source
  - name: upstream_repo
    run_list:
    - recipe[minitest-handler::default]
    - recipe[nginx::repo]
    - recipe[nginx::default]
    attributes:
      nginx:
        repo_source: nginx
  - name: ssl_module
    run_list:
    - recipe[minitest-handler::default]
    - recipe[nginx::http_ssl_module]
    - recipe[nginx::source]
