driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-5.11
  - name: centos-6.8
  - name: centos-7.2
  - name: debian-7.11
    run_list: apt::default
  - name: debian-8.5
    run_list: apt::default
  - name: fedora-24
    run_list: yum::dnf_yum_compat
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-16.04
    run_list: apt::default

suites:
  - name: default
    run_list:
      - recipe[nginx::default]
  - name: source
    run_list:
      - recipe[nginx::default]
    attributes:
      nginx:
        install_method: source
  - name: upstream_repo
    run_list:
      - recipe[nginx::repo]
      - recipe[nginx::default]
    attributes:
      nginx:
        repo_source: nginx
    excludes:
      - fedora-24
  - name: modules
    run_list:
      - recipe[nginx::source]
    attributes:
      nginx:
        source:
          modules:
            - nginx::headers_more_module
            - nginx::http_auth_request_module
            - nginx::http_echo_module
            - nginx::http_geoip_module
            - nginx::http_gzip_static_module
            - nginx::http_realip_module
            - nginx::http_v2_module
            - nginx::http_ssl_module
            - nginx::http_stub_status_module
            - nginx::naxsi_module
            - nginx::ngx_devel_module
            - nginx::ngx_lua_module
            - nginx::openssl_source
            - nginx::upload_progress_module
